// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr4QWO8D3PwtAsjVvQktSL_yZR-cfSpWw',
    appId: '1:1054085764584:web:c1bb96ed60ac8ee10ec05d',
    messagingSenderId: '1054085764584',
    projectId: 'macaronqr',
    authDomain: 'macaronqr.firebaseapp.com',
    databaseURL: 'https://macaronqr-default-rtdb.firebaseio.com',
    storageBucket: 'macaronqr.firebasestorage.app',
    measurementId: 'G-QKCK5Q130N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZXcDA8TAI3VPWHGuTxK7GXFKCR5Gm8bk',
    appId: '1:1054085764584:android:4ac4e1ba357108950ec05d',
    messagingSenderId: '1054085764584',
    projectId: 'macaronqr',
    databaseURL: 'https://macaronqr-default-rtdb.firebaseio.com',
    storageBucket: 'macaronqr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9Q68GkKOJA7pzseQdYNk0nEfPNcB3-_c',
    appId: '1:1054085764584:ios:5676f566d45518d40ec05d',
    messagingSenderId: '1054085764584',
    projectId: 'macaronqr',
    databaseURL: 'https://macaronqr-default-rtdb.firebaseio.com',
    storageBucket: 'macaronqr.firebasestorage.app',
    iosBundleId: 'com.example.macaronQr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9Q68GkKOJA7pzseQdYNk0nEfPNcB3-_c',
    appId: '1:1054085764584:ios:5676f566d45518d40ec05d',
    messagingSenderId: '1054085764584',
    projectId: 'macaronqr',
    databaseURL: 'https://macaronqr-default-rtdb.firebaseio.com',
    storageBucket: 'macaronqr.firebasestorage.app',
    iosBundleId: 'com.example.macaronQr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr4QWO8D3PwtAsjVvQktSL_yZR-cfSpWw',
    appId: '1:1054085764584:web:ab2da7e18fbfa5790ec05d',
    messagingSenderId: '1054085764584',
    projectId: 'macaronqr',
    authDomain: 'macaronqr.firebaseapp.com',
    databaseURL: 'https://macaronqr-default-rtdb.firebaseio.com',
    storageBucket: 'macaronqr.firebasestorage.app',
    measurementId: 'G-TDSNMT5379',
  );
}
